version: '3'

services:
  minio:
    extends:
      file: minio/compose.yml
      service: minio

  minio-init:
    extends:
      file: minio/compose.yml
      service: minio-init
    depends_on:
      - minio

  wireguard:
    extends:
      file: wireguard/compose.yml
      service: wireguard

  nginx:
    extends:
      file: nginx/compose.yml
      service: nginx
    depends_on:
      - minio
      - wireguard
      
  thumbnail:
    extends:
      file: thumbnail/compose.yml
      service: thumbnail
    depends_on:
      - minio


volumes:
  minio_data:
  wireguard_config: