version: "3"

services:
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9091:9091
    environment:
      MINIO_ROOT_USER: ingsh
      MINIO_ROOT_PASSWORD: ingsh
    command: server /data --console-address ":9091"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    
  minio-init:
    image: minio/mc
    container_name: minio-init
    environment:
      MINIO_SERVER: minio
      MINIO_ROOT_USER: ingsh
      MINIO_ROOT_PASSWORD: ingsh
      $MINIO_WEBHOOK_DOMAIN: $MINIO_WEBHOOK_DOMAIN
    volumes:
      - ./init:/init
    entrypoint: /init/init.sh
      