version: '3'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      PUID: 502
      PGID: 20
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
